spring:
  profiles:
    default: h2
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
server.port: 8080



#spring.datasource.platform: postgres
#spring.datasource.url: jdbc:postgresql://localhost:5432/todolist
#spring.datasource.username: postgres
#spring.datasource.password: 1111

#spring.jpa.defer-datasource-initialization=true

#spring.datasource.initialization-mode: always


spring.jpa.show-sql: true
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: validate


#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.softserve.itacademy: INFO

logging.file.name: logs/todolist.log
logging.file.clean-history-on-start: true

#logging.file: ${catalina.home}/logs/todolist.log